# Generated by Django 4.2.27 on 2026-01-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='estado_disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido')], db_column='estado_disponibilidad', default='Disponible', help_text='Estado de disponibilidad del producto', max_length=20),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='rutaimagen',
            field=models.CharField(blank=True, db_column='rutaimagen', help_text='URL o ruta de la imagen PNG/JPG del producto', max_length=200, null=True),
        ),
    ]
