# Generated by Django 4.2.27 on 2026-01-23 00:59

import apps.trayectoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0002_ventagarage_estado_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='fechafin',
            field=models.DateField(blank=True, db_column='fechafin', null=True, validators=[apps.trayectoria.models.validar_fecha_maxima]),
        ),
        migrations.AlterField(
            model_name='cursorealizado',
            name='fechainicio',
            field=models.DateField(blank=True, db_column='fechainicio', null=True, validators=[apps.trayectoria.models.validar_fecha_maxima]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(blank=True, db_column='fechafingestion', null=True, validators=[apps.trayectoria.models.validar_fecha_maxima]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(blank=True, db_column='fechainiciogestion', null=True, validators=[apps.trayectoria.models.validar_fecha_maxima]),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fechaproducto',
            field=models.DateField(blank=True, db_column='fechaproducto', null=True, validators=[apps.trayectoria.models.validar_fecha_maxima]),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fechareconocimiento',
            field=models.DateField(blank=True, db_column='fechareconocimiento', null=True, validators=[apps.trayectoria.models.validar_fecha_maxima]),
        ),
    ]
