# Generated by Django 4.2.27 on 2026-01-23 01:10

import apps.trayectoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0003_alter_cursorealizado_fechafin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateField(blank=True, db_column='fecha_publicacion', help_text='Fecha de publicación del producto (no mayor a 2026)', null=True, validators=[apps.trayectoria.models.validar_fecha_maxima]),
        ),
    ]
