# Generated by Django 4.2.27 on 2026-01-23 07:53

import apps.trayectoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectoria', '0004_ventagarage_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateField(blank=True, db_column='fecha_publicacion', null=True, validators=[apps.trayectoria.models.validar_fecha_maxima]),
        ),
    ]
