# Generated by Django 4.2.27 on 2026-01-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_datospersonales_foto_perfil_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='fondo_modern_url',
            field=models.URLField(blank=True, db_column='fondo_modern_url', help_text='URL del fondo para la plantilla Modern (imagen en blob)', null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='fondo_professional_url',
            field=models.URLField(blank=True, db_column='fondo_professional_url', help_text='URL del fondo para la plantilla Professional (imagen en blob)', null=True),
        ),
    ]
