# Generated by Django 4.2.27 on 2026-01-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_datospersonales_fondo_modern_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_datos_personales',
            field=models.BooleanField(db_column='mostrar_datos_personales', default=True, help_text='Mostrar información personal en el CV público'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_educacion',
            field=models.BooleanField(db_column='mostrar_educacion', default=True, help_text='Mostrar educación/cursos en el CV público'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_experiencias',
            field=models.BooleanField(db_column='mostrar_experiencias', default=True, help_text='Mostrar experiencia laboral en el CV público'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_academicos',
            field=models.BooleanField(db_column='mostrar_productos_academicos', default=True, help_text='Mostrar productos académicos en el CV público'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_laborales',
            field=models.BooleanField(db_column='mostrar_productos_laborales', default=True, help_text='Mostrar productos laborales en el CV público'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_reconocimientos',
            field=models.BooleanField(db_column='mostrar_reconocimientos', default=True, help_text='Mostrar reconocimientos en el CV público'),
        ),
    ]
