# Generated by Django 4.2.27 on 2026-01-22 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_datospersonales_mostrar_datos_personales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilidadCV',
            fields=[
                ('perfil', models.OneToOneField(db_column='idperfil', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='visibilidad_cv', serialize=False, to='perfil.datospersonales')),
                ('mostrar_datos_personales', models.BooleanField(db_column='mostrar_datos_personales', default=True, help_text='Mostrar información personal en el CV público')),
                ('mostrar_experiencias', models.BooleanField(db_column='mostrar_experiencias', default=True, help_text='Mostrar experiencia laboral en el CV público')),
                ('mostrar_educacion', models.BooleanField(db_column='mostrar_educacion', default=True, help_text='Mostrar educación/cursos en el CV público')),
                ('mostrar_reconocimientos', models.BooleanField(db_column='mostrar_reconocimientos', default=True, help_text='Mostrar reconocimientos en el CV público')),
                ('mostrar_productos_academicos', models.BooleanField(db_column='mostrar_productos_academicos', default=True, help_text='Mostrar productos académicos en el CV público')),
                ('mostrar_productos_laborales', models.BooleanField(db_column='mostrar_productos_laborales', default=True, help_text='Mostrar productos laborales en el CV público')),
            ],
            options={
                'db_table': 'VISIBILIDAD_CV',
            },
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_datos_personales',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_educacion',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_experiencias',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_productos_academicos',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_productos_laborales',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='mostrar_reconocimientos',
        ),
    ]
