# Generated by Django 4.2.27 on 2026-01-23 00:59

import apps.perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_visibilidadcv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visibilidadcv',
            name='mostrar_educacion',
        ),
        migrations.AddField(
            model_name='visibilidadcv',
            name='mostrar_cursos',
            field=models.BooleanField(db_column='mostrar_cursos', default=True, help_text='Mostrar cursos realizados en el CV público'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(db_column='fechanacimiento', validators=[apps.perfil.models.validar_fecha_maxima]),
        ),
    ]
